<?php
// $Id: views_bonus_panels_twocol_stk.module,v 1.2.2.2 2007/02/03 18:26:13 merlinofchaos Exp $
function views_bonus_panels_twocol_stk_views_style_plugins() {
  $items['panels_twocol_stk'] = array(
    'name' => t('Panels: Teasers, 1 top + 2 columns'),
    'theme' => 'views_bonus_panels_twocol_stacked',
    'summary_theme' => 'views_summary',
  );
  return $items;
}

/**
 * Because views doesn't currently support configuration options for
 * plugins, the best way to make configuration changes here is 
 * to override the theme.
 */
function theme_views_bonus_panels_twocol_stacked($view, $nodes, $type) {
  $teasers = true;
  $links = true;

  $content = array();
  foreach ($nodes as $count => $n) {
    $node = node_load($n->nid);
    if ($count == 0) {
      $section = 'top';
    }
    else if ($count % 2) {
      $section = 'left';
    }
    else {
      $section = 'right';
    }
    $content[$section] .= node_view($node, $teasers, false, $links);
  }
  return panels_print_layout('twocol_stacked', $content);
}
